### ISSUE TITLE
Customize the control buttons for the virtual joystick

### ISSUE THREAD

**Issue by climst** [emulatorjs/emulatorjs#891] opened 2024-09-13 19:50 UTC
Hello.
I would like to see in the future a function to customize the control buttons for the virtual joystick. To be able to move them and change their size.
![Screenshot_20240913-213855](https://github.com/user-attachments/assets/358176e8-25c5-4827-872d-d7b5a3f8d9a3)

**Comment by ethanaobrien** [comment] 2024-09-13 19:55
Closing as duplicate of #588

**Closed as completed by ethanaobrien** 2024-09-13 19:55 UTC
