### ISSUE TITLE
What folders structure on web server?

### ISSUE THREAD

**Issue by dosboxonline** [EmulatorJS/EmulatorJS#4] opened 2021-07-21 21:22 UTC
Error log in google chrome - 

loader.js:1 Uncaught ReferenceError: EJS_pathtodata is not defined
    at loader.js:1
(anonymous) @ loader.js:1

Place "loader.js" in same folder where "index.html" and in "/data/" folder and in "/emulatorjs/" and in "/emulatorjs/data/" and root. Also change path to "loader.js" file. I don't understand what needs to be changed in "loader.js" file.

**Comment by ethanaobrien** [comment] 2021-07-21 21:30
Nothing needs to be changed in the loader.js file. Your index.html is what needs to be changed. 
See the readme for more specific instructions, but the problem is with you not having declared EJS_pathtodata. The readme includes a HTML template for each system. Copy and paste this template into index.html and change the path to data (if needed) and set the path to the rom.

If this still does not work, please copy and paste everything inside your HTML file and send it here

**Comment by dosboxonline** [comment] 2021-07-21 21:31
It works! Add files from your Demo - "emulator.js" and "webrtc-adapter.js"

**Comment by ethanaobrien** [comment] 2021-07-21 21:33
The emulator.js and webrtc-adapter.js files in the demo are outdated. In the main repository, the files you seek are in the /data folder

**Comment by dosboxonline** [comment] 2021-07-21 21:36
I apologize for not looking at html. I used the one on the site www.emulatorjs.com and did not look that they are different. Thanks.

**Comment by ethanaobrien** [comment] 2021-07-21 21:38
Awesome! I'm glad you figured it out. Would you mind closing this issue?

**Comment by dosboxonline** [comment] 2021-07-21 21:44
Sure! Everything works. At first I tried to remove ads through the CSS. Then found your solution.

**Closed as completed** 2021-07-21 22:43 UTC
