### ISSUE TITLE
Still not work after change core

### ISSUE THREAD

**Issue by budi1175** [emulatorjs/emulatorjs#632] opened 2023-08-23 13:42 UTC
Hi I make change for psx to beetle-psx like your opinion but still not work. I get script that work from emulatorjs but it's different than mine. here is screenshot 
![screen2](https://github.com/EmulatorJS/EmulatorJS/assets/141638647/238cd5b7-8154-4a3e-b211-6649cac3cb2c)
![screen3](https://github.com/EmulatorJS/EmulatorJS/assets/141638647/aa899ecd-f93f-469c-a2c7-794ab0214e9b)
This is mine below 
![screen](https://github.com/EmulatorJS/EmulatorJS/assets/141638647/6568bd02-0e38-4975-abbc-d78224e6339f)
Work script there is watermark emulatorjs.comv.0.5.13. I think it is old script newest v 4. The set up screen different mine than script I try that working. Working script installed on retrogames.cc. Can I get work version like on retrogames.cc? or if I need to edit how to edit it?

**Comment by ethanaobrien** [comment] 2023-08-23 16:32
You can comment on closed issues.

**Comment by budi1175** [comment] 2023-08-23 23:08
Sorry but can you help me about this problem or still you search solution? why old version work but mine dont work? what different? Can I get old version ver 0.5.13 like on retrogames.cc? Ok I'll comment on closed issue too

**Comment by Ramaerel** [comment] 2023-08-24 00:46
Hi there!
I've done some experimenting and I've found that your issues seems to be specific to your rom- I've managed to get a copy sourced elsewhere to work. I can't link it here sorry, but if you can another rom it should work

**Comment by ethanaobrien** [comment] 2023-08-24 01:58
Since this is confirmed to be a rom issue, Im going to close this.

**Closed as completed by ethanaobrien** 2023-08-24 01:58 UTC
