### ISSUE TITLE
[Bug] Amiga WHloader - stuttering sound and slow fps during gameplay

### ISSUE THREAD

**Issue by shaylevary** [emulatorjs/emulatorjs#880] opened 2024-08-19 20:00 UTC
Hi,

First of all I would like to thank you for adding support for Amiga WHDLoader HDF files.

After updating to the latest version 4.1.1 which was released today, i've try to run WHDLoader file.

The first issue i've encouter is stuttering sound and slow fps during gameplay (this issue appears only on pc browsers, while when running on my mobile, it works ok).
 The second issue is when i've tried to change the paue zoom mode, the game canvas size didn't change (display size didn't change).

Here is console log:
[console.whdloader.error.log](https://github.com/user-attachments/files/16665547/console.whdloader.error.log)

**Comment by ethanaobrien** [comment] 2024-08-19 23:43
Toggle vsync?

**Comment by shaylevary** [comment] 2024-08-20 12:10
I will test the vsync toggle later today when i'll be back home and update you.

Regarding the "puae_zoom_mode_crop" - it doesn't change game canvas size when switching the zoom options, can you please check this bug?

**Comment by ethanaobrien** [comment] 2024-08-20 12:28
>it doesn't change game canvas size when switching the zoom options

Zoom will not change the canvas size, canvas is set to as big as it can. This is RetroArch, and is not a bug

**Comment by shaylevary** [comment] 2024-08-20 15:32
On the older version the puae_zoom_mode_crop option worked fine, this zoom option appears to stop working since latest version.

Maybe I can set the css ".ejs_canvas" to something else in order to achieve a larger game size as it worked before with the "puae_zoom_mode_crop" option.

Thank you

**Comment by ethanaobrien** [comment] 2024-08-20 16:09
That’s not how zooming works. If you feel like that will fix it feel free to try it, though I promise that’s the completely wrong direction and has nothing to do with the canvas

**Comment by shaylevary** [comment] 2024-08-20 16:46
Until you'll restore the changes you've made on the amiga core in order to make the zoom option work again, I'm looking for some alternative temporary solution, and changing the canvas css width and height can enlarge the game screen size.

**Comment by ethanaobrien** [comment] 2024-08-22 00:21
@shaylevary  have you been able to test with vsync disabled.

I believe @michael-j-green  has also had this issue on very specific hardware, which does make it a browser issue of some sort. It’s unlikely fixable from my side

**Comment by michael-j-green** [comment] 2024-08-22 00:24
I was running it on a Macbook M1 Pro in Safari and had some stuttering. Turned out it was because my laptop was in low power mode.

Once I disabled low power mode, the problem went away, and performance was back to where I expected it.

**Comment by shaylevary** [comment] 2024-08-22 05:26
There are games that require more processing power than other games. After I turned off the vsync, the problem was solved and all the games work smoothly without a stuttering problem.

Regarding the zoom view option, this option worked fine in your previous versions. Only in the latest version I noticed that this option does not work.
If you are interested, I can also write you in which specific version it worked properly.

Anyway, I solved it temporarily by changing the size of the canvas for all those games that display game picture on a small center part of the screen.

**Comment by ethanaobrien** [comment] 2024-08-22 13:05
> There are games that require more processing power than other games. After I turned off the vsync, the problem was solved and all the games work smoothly without a stuttering problem.

Since this has been resolved, I am closing this

> Regarding the zoom view option, this option worked fine in your previous versions. Only in the latest version I noticed that this option does not work.

This is likely something broken upstream, since I do not touch any of those settings themselves. You will need to wait until it's fixed upstream

**Closed as completed by ethanaobrien** 2024-08-22 13:05 UTC
