### ISSUE TITLE
Can not bind controls on iOS 16 Safari

### ISSUE THREAD

**Issue by kmstrube81** [emulatorjs/emulatorjs#457] opened 2023-01-09 00:02 UTC
Tested on Gameboy, PlayStation, and Nintendo 64 cores. Gamepads are detected but emulator does not respond when trying to bind to a game pad input.

Tested with razer kishi v2 connected via lightning port and dual sense PlayStation controller connected via Bluetooth and both controllers are detected but neither can bind controls.

no issues binding Xbox 360 controller on windows 10 and chrome . As far as I can tell this is an iOS issue

**Comment by ethanaobrien** [comment] 2023-01-09 01:01
This doesn't surprise me, iOS is know to be minimally compatible with anything not Apple. I can't do anything about this, unless you can find another website that uses gamepads and it actually works.

**Comment by kmstrube81** [comment] 2023-01-09 01:32
eNGE is a PS1 emulator ( [github link](https://github.com/kootstra-rene/enge-js) ) written in JavaScript that detects the game pad input from these controllers but does not run games at full speed.

emulator js’ PS1 core runs the games at full speed and is playable with on screen touch controls. It also recognizes the gamepad but does not respond to input during the control rebinding screen. (Shown in screenshot attached)

![4E6C569F-3E76-4E0C-90BF-0FFEE6205B0D](https://user-images.githubusercontent.com/6616551/211229046-fa938edc-5349-42ab-97d1-0777e0ec0240.png)

**Comment by ethanaobrien** [comment] 2023-01-09 01:48
I think I see what the issue is. I'll get this fixed

**Comment by ethanaobrien** [comment] 2023-07-18 17:16
This should be fixed

**Closed as completed by ethanaobrien** 2023-07-18 17:16 UTC
Labels: bug
