### ISSUE TITLE
Support N64 ctrl and show the “cross arrow keys”

### ISSUE THREAD

**Issue by nenge123** [emulatorjs/emulatorjs#120] opened 2022-02-05 05:54 UTC
relase
![微信图片_20220205164137](https://user-images.githubusercontent.com/16117315/152635044-10dee832-894f-4aac-a529-7847202794bb.png)

//emulator.js other change or   style=>b_menu{css code}
'b_c': 'ejs--fbd492618ebsd464fbcd1c9185cd14',
change
'b_menu': 'ejs--fbd492618ebsd464fbcd1c9185cd14',

```css
<!--  need css -->
.ejs-arrow{position:absolute;bottom:250px;width:150px;margin:auto;left:0;right:0;display:block;}.ejs-arrow .b_up{left:0;top:0;left:50px;font-size:12px;}.ejs-arrow .b_down{left:0;top:100px;left:50px;font-size:12px;}.ejs-arrow .b_left{left:0;top:50px;left:0;font-size:12px;}.ejs-arrow .b_right{left:0;top:50px;left:100px;font-size:12px;}.ejs-arrow[data-pos="left"]{left: 10px !important;right: auto;bottom: 180px;}.ejs-arrow[data-pos="left"]>div{border-radius: 15px !important;}@media screen and (max-height:500px){.ejs-arrow{left: 80px;bottom: calc(100vh - 80px);right: auto;}}
```

```javascript
//emu-main.js
'toggleVirtualGamepad': function (initBool) {
    //虚拟按键
    let BtnDATA = _0x378b5c,
        BindClassName =  _0x449eac;
this.translate = e=>e;
this.GamepadMap = {0:"B",1:"Y",2:"SELECT",3:"START",4:"UP",5:"DOWN",6:"LEFT",7:"RIGHT",8:"A",9:"X",10:"L",11:"R",12:"L2",13:"R2",14:"L3",15:"R3",16:"L STICK RIGHT",17:"L STICK LEFT",18:"L STICK DOWN",19:"L STICK UP",20:"R STICK RIGHT",21:"R STICK LEFT",22:"R STICK DOWN",23:"R STICK UP",24:"QUICK SAVE STATE",25:"QUICK LOAD STATE",26:"CHANGE STATE SLOT"};
    //虚拟按键
if (null === BtnDATA.virtualGamepadContainer) {
    let container = this.elements.container,
        QueryS = className => container.querySelector(className),
        PadCreatB = (str,c)=>{
        let d = {};
        if(c != undefined){
            d[str] = !c;
            return BindClassName(d);
        }
        let keyV = str.split('::'),
            keyid = syncInputMap[str];
        if(!keyid) return '';
        d['buttons'] = !0;
        d['b_'+keyV[0].toLowerCase()] = !0;
        let className = BindClassName(d);
        return `<div class="${className}" data-buttonid="${keyid}">${this.translate(keyV[1]||str)}</div>`;
        },
        ETYPE = ['mousedown', 'mouseup', 'mouseout', 'mousemove'],
        syncInputMap ={},
        syncInputMapSTATE ={},
        syncValue = vi=>16<=vi&&vi<= 23 ? 0x7fff:1,
        touch_class = PadCreatB('touch',0),
        toggleClass = (i,v)=>{
            let str = GamepadMap[i];
            if(!str) return ;
            let newstr = 'b_'+str.split('::')[0].toLowerCase(),
                elm = QueryS('.'+PadCreatB(newstr,0));
            if(!elm) return ;
            elm.classList[v?'add':'remove'](touch_class);

        },
        SENDsyncInput = state=>{
            state = state ||{};
            for(var i in syncInputMapSTATE){
                if(state[i] != undefined){
                    let v = state[i] ? syncValue(i) :0;
                    //i=24 is burst
                    BtnDATA.syncInput(0,i,v);
                    syncInputMapSTATE[i] = v;
                    if(v){
                        toggleClass(i,1);
                        //touchClass
                    }
                }else if(syncInputMapSTATE[i] != 0){
                    BtnDATA.syncInput(0,i,0);
                    syncInputMapSTATE[i] = 0;
                    toggleClass(i,0);
                }
            }

        },
        ArrowOut = false,
        ArrowElm = (bool)=>{
            if(!bool) return '';
            return `<div class="${PadCreatB('ejs-arrow',0)}" data-pos="${bool}">${PadCreatB('UP')}${PadCreatB('LEFT')}${PadCreatB('RIGHT')}${PadCreatB('DOWN')}</div>`
        },
        GamepadMap = this.GamepadMap,
        delkey = e=>e.split(',').forEach(val=>delete GamepadMap[val]),
        G = {X:'X',Y:'Y',A:'A',B:'B',L:'L',R:'R'},
        ctrlSTICK_key = ['RIGHT','UP','LEFT','DOWN'];
    if(['gba','vbanext','gb','nes'].includes(this.system)){
        delkey('1,9');
        if(['gb','nes'].includes(this.system)){
            delkey('10,11');
        }
        ArrowOut = 'left';
    }else if('n64' == this.system){
        delkey('1,9,10');
        G.X += '::R';
        G.Y += '::Z';
        G.L += '::COMBOKEY';
        G.R += '::L';
        GamepadMap[12] = G.X;
        GamepadMap[11] = G.Y;
        GamepadMap[23] = G.R;
        GamepadMap['COMBO'] = G.L;
        ArrowOut = 'center';
        ctrlSTICK_key = ctrlSTICK_key.map(posvalue=>'L STICK '+posvalue);
    };
    GamepadMap['MENU'] = 'MENU';//c  b_c
    for(var index in GamepadMap){
        if(!isNaN(index)){
            syncInputMapSTATE[index] = 0;
        }
        syncInputMap[GamepadMap[index]] = index;
    }
    BtnDATA.virtualGamepadContainer = CreatElm('div', {'class': PadCreatB('ejs-virtual-gamepad',0),'hidden': ''});
    container.appendChild(BtnDATA.virtualGamepadContainer);
    BtnDATA.virtualGamepadContainer.innerHTML = `<div class="${PadCreatB('virtual-gamepad',0)} virtual-gamepad-${this.system}" style="display: block;">${ArrowElm(ArrowOut)}<div class="${PadCreatB('top',0)}">${PadCreatB(G.L)}${PadCreatB(G.R)}</div><div class="${PadCreatB('left',0)}"></div><div class="${PadCreatB('center',0)}">${PadCreatB('SELECT')}${PadCreatB('START')}${PadCreatB('MENU')}</div><div class="${PadCreatB('right',0)}">${PadCreatB(G.A)}${PadCreatB(G.B)}${PadCreatB(G.X)}${PadCreatB(G.Y)}</div></div>`;
    _0x132da7(BtnDATA.virtualGamepadContainer, !initBool);
    if(ArrowOut != 'left'){
        var ctrlSTICK = _0x3a58c8.a['create']({
            'zone': QueryS(`.${PadCreatB('ejs-virtual-gamepad',0)} .${PadCreatB('left',0)}`),
            'mode': 'static',
            'position': {'left': '50%','top': '50%'},
            'color': '#2b92db94',
        });
        ctrlSTICK.state = {};
        ctrlSTICK.reset = e=>{
            SENDsyncInput(ctrlSTICK.state);
            ctrlSTICK.state = {};
        };
        ctrlSTICK.on('end',event=>{
            ctrlSTICK.reset();
        });
        ctrlSTICK.on('move',(event, eventData)=>{
            var degree = eventData.angle['degree'];
            ctrlSTICK.reset();
            if(!degree) return;
            let a = degree/90,
                b = Math.floor(a),
                c = a - b,
                bkey = syncInputMap[ctrlSTICK_key[b]],
                d = (b+1)%4,
                dkey = syncInputMap[ctrlSTICK_key[d]];
                if(c<=0.65){
                    ctrlSTICK.state[bkey] = 0;
                    BtnDATA.syncInput(0,bkey,syncValue(bkey));
                    if(c>=0.35){
                        ctrlSTICK.state[dkey] = 0;
                        BtnDATA.syncInput(0,dkey,syncValue(dkey));
                    }
                }else{
                    ctrlSTICK.state[dkey] = 0;
                    BtnDATA.syncInput(0,dkey,syncValue(dkey));
                }
        });
    }else{
        QueryS(`.${PadCreatB('ejs-virtual-gamepad',0)} .${PadCreatB('left',0)}`).style.display="none";
    }
    QueryS(`.${PadCreatB('ejs-virtual-gamepad',0)} .${PadCreatB('b_menu',0)}`).style.zIndex="2";
    if(GamepadMap['COMBO'])QueryS(`[data-buttonid="COMBO"]`).style.fontSize="12px";
    if ("ontouchstart" in document) ETYPE = ['touchstart', 'touchmove', 'touchcancel', 'touchend'];
    this.SEND = e=>SENDsyncInput(e);
    ETYPE.forEach(
        val=>BtnDATA.virtualGamepadContainer.addEventListener(val,event=>{
            let ct = event.changedTouches && event.changedTouches[0],
            cte = ct && document.elementFromPoint(ct.pageX, ct.pageY),
            elm = cte ||event.target,
            type = event.type,
            key = elm&&elm.getAttribute('data-buttonid'),
            keyState = {};
            if(['touchend','mouseup'].includes(type)&&isNaN(key)){
                if(key == 'MENU'){
                    this.elements.container.classList.toggle(this.config['classNames']['hideControls']);
                }else if(key == 'COMBO'){
                    elm.classList.toggle('active');
                    BtnDATA.syncInput(0,24, elm.classList.contains('active'));
                }
            }else if (event.touches && event.touches.length > 0) {
                for (var i = 0; i < event.touches.length; i++) {
                    var t = event.touches[i];
                    var newElm = document.elementFromPoint(t.pageX, t.pageY),
                        k = newElm&&newElm.getAttribute('data-buttonid');
                        if (!isNaN(k))keyState[k] = 1;
                }
            }else{
                if (type == "mouseup") {
                    this.mousedownHold = false;
                } else if (this.mousedownHold == true || type == 'mousedown') {
                    this.mousedownHold = true;
                    if (!isNaN(key))keyState[key] = 1;
                }
            }
            SENDsyncInput(keyState);
            event.preventDefault();
            event.stopPropagation();
            return false;
        })
    );
    } else _0x132da7(BtnDATA.virtualGamepadContainer, !initBool);
}
```
![屏幕截图(25)](https://user-images.githubusercontent.com/16117315/152630407-b318ad0e-f0be-4b9e-ad3d-ae3f868b162c.jpg)
![微信图片_20220205132552](https://user-images.githubusercontent.com/16117315/152629933-0c0a3f99-50dd-4140-9ae8-6048ebfb951e.png)

**Comment by nenge123** [comment] 2022-02-05 06:35
There is a logical error in the previous code, the correct one should be
c~
3.65 ~ 0  is right //N64 L STICK RIGHT
0.35 ~ 0.65 is right up //N64 L STICK RIGHT & L STICK  UP
0.65 ~ 1 is up //N64 L STICK  UP
```javascript
        ctrlSTICK.on('move',(event, eventData)=>{
            var degree = eventData.angle['degree'];
            ctrlSTICK.reset();
            if(!degree) return;
            let keyState = {},
                a = degree/90,
                b = Math.floor(a),
                c = a - b,
                bkey = syncInputMap[ctrlSTICK_key[b]],
                d = (b+1)%4,
                dkey = syncInputMap[ctrlSTICK_key[d]];
                console.log(c);
                if(c<=0.65){
                    ctrlSTICK.state[bkey] = 0;
                    BtnDATA.syncInput(0,bkey,syncValue(bkey));
                    if(c>=0.35){
                        ctrlSTICK.state[dkey] = 0;
                        BtnDATA.syncInput(0,dkey,syncValue(dkey));
                    }
                }else{
                    ctrlSTICK.state[dkey] = 0;
                    BtnDATA.syncInput(0,dkey,syncValue(dkey));
                }
        });
```

**Comment by ethanaobrien** [comment] 2022-02-05 15:33
Duplicate of #116 

This doesn't even look like the code from this repository. You're probably editing a clone

**Closed as completed by ethanaobrien** 2022-02-05 15:33 UTC
