### ISSUE TITLE
NDS Sound is Very Broken

### ISSUE THREAD

**Issue by ReedGraf** [emulatorjs/emulatorjs#268] opened 2022-06-01 02:00 UTC
Unsure if this is a known bug but the ROMs loaded always have laggy audio. The log file is attached below and may have some other gibberish in it from other things in the HTML. 

Beta Emulator: No
System: Nintendo DS
Rom: Lego Star Wars - The Complete Saga

[-1654048433306.log](https://github.com/ethanaobrien/emulatorjs/files/8810450/-1654048433306.log)

**Comment by ethanaobrien** [comment] 2022-06-03 18:58
@ReedGraf

Can you tell me if this also occurs when using beta?

**Comment by ethanaobrien** [comment] 2022-06-03 19:07
Wait a second. Your running from a file... how is it even possible that you got it to run?

Just realized what the issue is. Your device isn’t fast enough. Use frameskip (setting button in corner)

(Also, thanks for including config details and a log of the console)

**Comment by ReedGraf** [comment] 2022-06-03 21:39
I'm running the html file locally and using the resources for EmulatorJS hosted on your github.io link provided. The nds rom itself is hosted on one of my repo's github.io pages.

Even when maxing out the frameskip to 9 or hosting the html on a github page it still has the same exact choppy sound. I'm pretty sure that my hardware shouldn't be a problem because whenever I open task manager it's doing just fine (My RAM is DDR3 if that makes any difference, I got an old ThinkPad mobile workstation).

I've included a pic of the game running with task manager on the screen (When screenshot was taken the problem was still occuring). Let me know if this helps or if you need more info

![image](https://user-images.githubusercontent.com/78926953/171957030-2563dcbf-fb85-4f06-9f15-fff5702c8ad9.png)

**Comment by ethanaobrien** [comment] 2022-06-03 21:42
I can look at this. Not sure if it can be fixed though

**Comment by ReedGraf** [comment] 2022-06-03 21:43
Ok, thanks. 😄

**Comment by ethanaobrien** [comment] 2022-06-03 23:53
Threading may fix this... this would only be fixed on the beta

**Comment by ReedGraf** [comment] 2022-06-04 00:47
Nope, it only made it worse if anything.

Edit: Beta is enabled btw

**Comment by ethanaobrien** [comment] 2022-06-04 03:25
Ok, thanks. Threading should fix. I’ll test when I get a chance

**Comment by ethanaobrien** [comment] 2022-08-09 23:39
I did some looking, its at the best it can be right now. Maybe once the emulation technology gets better for the web

**Closed as completed by ethanaobrien** 2022-08-09 23:39 UTC
Labels: bug, New cores
