### ISSUE TITLE
NetPlay info "please"

### ISSUE THREAD

**Issue by mariamariasilva1933** [EmulatorJS/EmulatorJS#897] opened 2024-09-17 14:27 UTC
Does netplay work on this version of the emulator?
I really want to play online with my friends...
Are you working on netplay? Even if there are bugs...
I just wanted to play a little.
Thanks to everyone involved.

**Comment by jamesjamesbond2001** [comment] 2024-09-17 16:35
release netplay v4 with bugs for test and fix

**Comment by ethanaobrien** [comment] 2024-09-17 17:29
No, netplay is not supported. Its partially implemented though does not work. I don't think you'd like to be playing with bugs where one guy is dead on one screen, and he's still alive on the other, so no.

I'm not actively working on netplay, or even really planning to, partially because of how much the topic comes up. The concept of netplay itself is mathematically impossible, and is not something that can just be done. Its not simple, not at all.

As always, if you want something done, the best way to get it there is to do it yourself.

Many users here comment on how the emulatorjs.com "version" of the emulator supports netplay and this one does not, though that netplay is slow and buggy. I'm not going to release an unusable feature

Closing as duplicate of #590

**Closed by ethanaobrien** 2024-09-17 17:29 UTC
