### ISSUE TITLE
加载游戏时页面会卡住, 呈现假死状态   when loading game, page is dead 

### ISSUE THREAD

**Issue by FancyTiger** [emulatorjs/emulatorjs#441] opened 2022-12-03 09:45 UTC
when loading game, page is dead ;  but when I open F12 in advance,  emulatorjs works and don't freezed

my OS : win10; my explorer : edge 107; 

I caught error log  in Firefox , it like this: 

Uncaught 
Object { node: undefined, setErrno: setErrno(errno), errno: 44, message: "FS error", stack: "ensureErrnoError@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:51971\nstaticInit@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:52177\n@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:182545\n_0x54d695@http://localhost:5566/data/emu-main.js?v=31:2004:44\nwindow.EJS_main/create/_0x4f0fcc/<@http://localhost:5566/data/emu-main.js?v=31:2016:29\n_0xbae705@http://localhost:5566/data/emu-main.js?v=31:255:23\n_0x21d6a1@http://localhost:5566/data/emu-main.js?v=31:2020:76\n" }

or waning log: 
Script terminated by timeout at:
process@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:84416
block@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:85406
_RWebAudioWrite@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:86583
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[2025]:0x1f3a0b
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[923]:0x822e3
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[4845]:0x2fbe57
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[2347]:0x20cc5f
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[316]:0xf43a
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[3181]:0x24647a
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[2345]:0x20bdd3
@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval line 1 > WebAssembly.instantiate:wasm-function[5674]:0x3557e7
callUserCallback@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:68357
runIter@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:69836
Browser_mainLoop_runner@http://localhost:5566/data/emu-main.js?v=31 line 2004 > eval:1:67920

**Comment by ethanaobrien** [comment] 2022-12-03 16:37
Duplicate of #416  please check for existing issues before opening a new one

**Closed as completed** 2022-12-03 16:37 UTC
