### ISSUE TITLE
Ability to change disk (playstation)

### ISSUE THREAD

**Issue by sDetective** [emulatorjs/emulatorjs#217] opened 2022-05-03 19:48 UTC
I was thinking that for the playstation roms there could be a disc changer as a option like a load state but discs

**Comment by ethanaobrien** [comment] 2022-05-03 19:51
This is called reloading the page? Like wdym. provide detail and maybe ill re-open

**Comment by Ramaerel** [comment] 2022-05-04 03:35
I think he means to change from disc 1 to disc 2 in a game. I think simply creating a download save at the disc swap scene, and then loading the save after loading the disc 2 iso will work

**Comment by dosboxonline** [comment] 2022-05-04 09:27
It works, but not for all games. Metal Gear Solid and Heart of Darkness - these games require open/close cd tray (I/0 cd tray dip switch).

**Comment by ethanaobrien** [comment] 2022-05-04 12:17
This would be complicated

**Comment by ethanaobrien** [comment] 2022-05-06 16:38
Just realized, this is a duplicate of #143

**Closed as completed by ethanaobrien** 2022-05-06 16:38 UTC
Labels: duplicate, enhancement
