### ISSUE TITLE
NetPlay & N64

### ISSUE THREAD

**Issue by c22dev** [emulatorjs/emulatorjs#489] opened 2023-03-08 18:38 UTC
When a user connect to a N64 net play room, the game on the one who join freeze after the loading alert.
Then, when restarting/resetting the game, it loads back a few times and works. Do you know what could cause this ?

**Comment by Cattn** [comment] 2023-04-06 14:40
This is a duplicate of #437

**Comment by ethanaobrien** [comment] 2023-04-06 14:41
That is correct. I'm going to close this

**Closed as completed** 2023-04-06 14:41 UTC
