### ISSUE TITLE
[Request] Add option to add your own BIOS in demo

### ISSUE THREAD

**Issue by Norbtails97** [emulatorjs/emulatorjs#804] opened 2024-03-18 21:26 UTC
On the demo, is there a workaround to install bios on the demo? for example, you wnt to play sonic cd. but you need a sega cd bios to run with it. can you make it possible to ADD the bios first, then the ROM?

**Comment by ethanaobrien** [comment] 2024-03-19 03:00
Duplicate of #249. 

It's a **demo**, it is not meant to play every game, and will stay that way.

**Comment by ethanaobrien** [comment] 2024-03-19 03:00
Though to answer your question just zip it with the rom

**Closed as completed by ethanaobrien** 2024-03-19 03:00 UTC

**Comment by Norbtails97** [comment] 2024-03-19 15:21
really? ok. ty!
