### ISSUE TITLE
Netplay not connect same screen 

### ISSUE THREAD

**Issue by lyarinet** [emulatorjs/emulatorjs#299] opened 2022-07-28 10:17 UTC
Netplay not connect same screen im trying to connect game 2 pc's pc1 create a room like a XYZ and connect game netplay and
pc2 join a room XYZ but screen can't connect same

**Comment by ethanaobrien** [comment] 2022-07-28 15:42
Duplicate of #69

**Closed as completed by ethanaobrien** 2022-07-28 15:42 UTC
